### PR TITLE
Rename airbrake to django_airbrake to avoid namespace collision with airbrake-python

### PR DESCRIPTION
**Pull request by yorinasub17**
Hello!

This renames the airbrake package in here to django_airbrake, since it collides with [airbrake-python](https://github.com/airbrake/airbrake-python). We need both, since we also need a module to report errors from celery which is outside of the regular django request-response cycle, and the name collision was causing problems.

Also updated the README to include the bit about adding the middleware to the list.

### CODE REVIEW

**Comment by cyberjoac** [comment]
+1

**Comment by kyrylo** [comment]
Hey! Could you please rebase?

**Comment by kyrylo** [comment]
Ping.

**Comment by kyrylo** [comment]
This shouldn't be a problem once https://github.com/airbrake/airbrake-python/issues/30 is resolved. (we should merge these two repos).

**Comment by yorinasub17** [comment]
Sorry I missed the request for rebase, but airbrake/airbrake-python#30 makes sense. Will continue the conversation there.

**Pull request closed without merging**
