### PR TITLE
Get environment variable from airbrake settings dict

### PR DESCRIPTION
**Pull request by peleccom**
Get environment variable from airbrake settings dict

### CODE REVIEW

**Comment by kyrylo** [comment]
Thanks for the PR, @peleccom. Was this simply broken? Syntax error?

**Comment by peleccom** [comment]
According to the document the ENVIRONMENT should be taken from the AIRBRAKE  dictionar in settings.py.

`# Airbrake settings
AIRBRAKE = {
    'API_KEY': 'YOUR_PROJECT_API_KEY',
    'USE_SSL': True,
    'TIMEOUT': 5,
    'ENVIRONMENT': 'production',
}`

But ENVIRONMENT variable in the global  settings namespace used.

**Comment by mmcdaris** [comment]
> ENVIRONMENT variable in the global settings namespace used.

Right you are! :+1:. I just tested this out and even though I had production set in the AIRBRAKE dictionary the error was reported from the development environment with a locally running server.

LGTM

**Comment by peleccom** [comment]
Sorry, it didn't fix the problem. Please see updated commit

**Pull request merged**
